<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPnee3gw\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPnee3gw/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerPnee3gw.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerPnee3gw\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerPnee3gw\appProdProjectContainer([
    'container.build_hash' => 'Pnee3gw',
    'container.build_id' => 'a37ad542',
    'container.build_time' => 1629830892,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPnee3gw');
